spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leetsBlog?serverTimezone=Asia/Seoul
    username: root
    password: 2323
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true