spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leets_blog?serverTimezone=Asia/Seoul
    username: root
    password: 1111
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
  show-sql: true