server:
  port: 8080

spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://db:3306/leets_blog?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    api-docs-path: /v3/api-docs
  info:
    title: "Leets 6th 블로그 과제 API DOC"
    version: "v1.0.0"
    description: "게시물 CRUD 기능에 대한 API 명세서입니다."

# JWT (JSON Web Token) 설정
jwt:
  secret: "W2Bxf8LRrTei5thxLZbG4cQi/lDeXogj9P3n+FJmNRga8WHiRdph1F9o/lLQT7epnovSQGMfAsmwX4UngWp+ng=="
  access-token-expiration-ms: 3600000  # 1시간
  refresh-token-expiration-ms: 604800000 # 7일

# Kakao
kakao:
  client-id: 1000bf8964ec857718ba58aceba1c155
  redirect-uri: http://localhost:8080/auth/login/kakao
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me