server:
  port: 8080

spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://localhost:3306/leets_blog?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    api-docs-path: /v3/api-docs
  info:
    title: "Leets 6th 블로그 과제 API DOC"
    version: "v1.0.0"
    description: "게시물 CRUD 기능에 대한 API 명세서입니다."