server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: "Leets 6th Blog API Docs"
    version: "v1.0.0"
    description: "블로그 프로젝트 API 명세서입니다."


jwt:
  secret: "YOUR_SUPER_SECRET_JWT_KEY_NEEDS_TO_BE_VERY_LONG_AND_SECURE_REPLACE_THIS_NOW"
  access-token-expiration-ms: 3600000

