spring.application.name=BlogApplication

#REST API KEY
kakao.login.api_key=67fa70c37870452229b26c75c181e4fe

#client-secret
kakao.login.client_secret=${JWT_SECRET_KEY}

# code
kakao.login.redirect_uri=http://localhost:8080/oauth/kakao/code
kakao.login.uri.code=/oauth/authorize
kakao.login.uri.base=https://kauth.kakao.com

# get token
kakao.login.uri.token=/oauth/token

# kakao login
kakao.api.uri.base=https://kapi.kakao.com
kakao.api.uri.user=/v2/user/me