spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?serverTimezone=Asia/Seoul
    username: root
    password: 8637
  jpa:
    hibernate:
      ddl-auto: update   # 개발 단계에서는 update / 운영은 validate 권장
    properties:
      hibernate:
        format_sql: true
    show-sql: true