version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: leets_blog  # application.yml의 DB명과 일치
      TZ: Asia/Seoul
    command: [
      "--performance-schema=off",
      "--innodb-buffer-pool-size=64M"
    ]
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      interval: 3s
      start_period: 25s

  springapp:
    image: sxvxnxwt/leets-blog:latest  # Docker Hub에 올라갈 이미지 이름
    container_name: springapp
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/leets_blog?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      TZ: Asia/Seoul
    networks:
      - mynetwork

volumes:
  db-data:

networks:
  mynetwork:
    driver: bridge
