spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogDB?serverTimezone=Asia/Seoul
    username: root
    password: 0305
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true